### ISSUE TITLE
How to properly maintain this docker instance if I want to change prosody configuration?

### ISSUE THREAD

**Issue by solus-hq** [ichuan/prosody#1]
@ichuan Thanks for your work and for sharing this project publicly!

I have a question regarding changes in configuration files. How do I update and restart the docker image having removed certain modules from configuration?

**Comment by ichuan** [comment]
@solus-hq 
I think you should maintain and use your customized config file instead of the default one:
1. First, copy and customize the config from a running docker instance
   ```bash
   docker cp iprosody:/etc/prosody/prosody.cfg.lua .
   # modify prosody.cfg.lua
   ```
2. Second, use the modified config file when running docker instance
   ```bash
   docker run --rm -itd --name iprosody -v $PWD/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua ...
   ```
The docker image upgrades mainly introduce new versions of prosody and prosody-modules, so mostly your customized config file will work across different versions of docker images. But if there's  any issues upgrading, try diff and merge changes from new prosody.cfg.lua file.
